apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordsmith
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AtongTerry/ArgoCD-wordsmith.git
    targetRevision: HEAD
    path: helm/wordsmith_deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: wordsmith
  SyncPolicy: 
    SyncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true