# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmith-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsmith-db
  template:
    metadata:
      labels:
        app: wordsmith-db
    spec:
      containers:
      - name: wordsmith-db
        image: "{{ .Values.image.db.repository }}:{{ .Values.image.db.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "wordsmith"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: wordsmith-db
spec:
  selector:
    app: wordsmith-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
