apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordsmith-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordsmith-api
  template:
    metadata:
      labels:
        app: wordsmith-api
    spec:
      containers:
      - name: wordsmith-api
        image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: wordsmith-db
        - name: DB_PORT
          value: "5432"
        - name: DB_PORT
          value: wordsmith_db
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: wordsmith-api
spec:
  type: LoadBalancer
  selector:
    app: wordsmith-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
